name: Build firmware

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/hadzhioglu/padavan-ng
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc libssl-dev build-essential
          wget http://ftp.gnu.org/gnu/libc/glibc-2.34.tar.gz
          tar -xvf glibc-2.34.tar.gz
          cd glibc-2.34
          mkdir build
          cd build
          ../configure --prefix=/opt/glibc-2.34
          make -j$(nproc)
          sudo make install
          export LD_LIBRARY_PATH=/opt/glibc-2.34/lib:$LD_LIBRARY_PATH

      - name: Get variables
        run: |
          sed -i 's|\r$||g' variables build.config
          . <(cat variables build.config)
          PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
          for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
            echo "$v=${!v}" >> $GITHUB_ENV
          done

      - name: Download sources and toolchain
        run: |
          git config --global --add safe.directory '*'
          git clone -b "$PADAVAN_BRANCH" "$PADAVAN_REPO" padavan
          cd padavan/toolchain-mipsel
          chmod +x dl_toolchain.sh
          ./dl_toolchain.sh
          cd ../../

      - name: Apply custom configurations
        run: |
          cp build.config padavan/trunk/configs/templates/$TNAME.config
          cd padavan/trunk
          if [ -f "../../$CUSTOM_SCRIPT" ]; then
            cp "../../$CUSTOM_SCRIPT" .
            chmod +x $CUSTOM_SCRIPT
            ./$CUSTOM_SCRIPT
          fi
          cd ../../

      - name: Compile the firmware
        run: |
          MAKEFILE_PATH=$(find . -type f -name "Makefile" | grep "openvpn")
          if [ -z "$MAKEFILE_PATH" ]; then
              echo "Error: Makefile not found"
              exit 1
          fi
          sed -i 's/-Wno-stringop-truncation//g' "$MAKEFILE_PATH"
          cd padavan/trunk
          fakeroot ./build_firmware_modify $TNAME 0
          mkdir -p ../firmware
          mv images/*.trx ../firmware/
          cd ../../

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: padavan/firmware/*.trx
